// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package protobuff

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HttpRequest struct {
	Greeting             string            `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	Infos                map[string]string `protobuf:"bytes,2,rep,name=infos,proto3" json:"infos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HttpRequest) Reset()         { *m = HttpRequest{} }
func (m *HttpRequest) String() string { return proto.CompactTextString(m) }
func (*HttpRequest) ProtoMessage()    {}
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *HttpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRequest.Unmarshal(m, b)
}
func (m *HttpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRequest.Marshal(b, m, deterministic)
}
func (m *HttpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRequest.Merge(m, src)
}
func (m *HttpRequest) XXX_Size() int {
	return xxx_messageInfo_HttpRequest.Size(m)
}
func (m *HttpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRequest proto.InternalMessageInfo

func (m *HttpRequest) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func (m *HttpRequest) GetInfos() map[string]string {
	if m != nil {
		return m.Infos
	}
	return nil
}

type HttpResponse struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	Details              []string `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpResponse) Reset()         { *m = HttpResponse{} }
func (m *HttpResponse) String() string { return proto.CompactTextString(m) }
func (*HttpResponse) ProtoMessage()    {}
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *HttpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpResponse.Unmarshal(m, b)
}
func (m *HttpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpResponse.Marshal(b, m, deterministic)
}
func (m *HttpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpResponse.Merge(m, src)
}
func (m *HttpResponse) XXX_Size() int {
	return xxx_messageInfo_HttpResponse.Size(m)
}
func (m *HttpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HttpResponse proto.InternalMessageInfo

func (m *HttpResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *HttpResponse) GetDetails() []string {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*HttpRequest)(nil), "HttpRequest")
	proto.RegisterMapType((map[string]string)(nil), "HttpRequest.InfosEntry")
	proto.RegisterType((*HttpResponse)(nil), "HttpResponse")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xdd, 0x2d, 0x55, 0x3b, 0x6d, 0x41, 0x83, 0xd2, 0x65, 0x4f, 0x65, 0x4f, 0xbd, 0x34,
	0x42, 0xbd, 0x14, 0x0f, 0x1e, 0x14, 0xa1, 0x5e, 0xb7, 0x07, 0xc1, 0x5b, 0x6a, 0x67, 0x43, 0x30,
	0x24, 0x31, 0x99, 0x2d, 0xec, 0xdf, 0xf0, 0x17, 0xcb, 0x6e, 0x6c, 0xbb, 0xb7, 0xf9, 0x5e, 0xe6,
	0xbd, 0x3c, 0x06, 0x80, 0x30, 0x10, 0x77, 0xde, 0x92, 0x2d, 0x7e, 0x13, 0x18, 0x6f, 0x88, 0x5c,
	0x89, 0x3f, 0x35, 0x06, 0x62, 0x39, 0x5c, 0x4b, 0x8f, 0x48, 0xca, 0xc8, 0x2c, 0x99, 0x27, 0x8b,
	0x51, 0x79, 0x62, 0xb6, 0x84, 0xa1, 0x32, 0x95, 0x0d, 0x59, 0x3a, 0x1f, 0x2c, 0xc6, 0xab, 0x19,
	0xef, 0x19, 0xf9, 0x7b, 0xfb, 0xf2, 0x66, 0xc8, 0x37, 0x65, 0xdc, 0xca, 0xd7, 0x00, 0x67, 0x91,
	0xdd, 0xc0, 0xe0, 0x1b, 0x9b, 0xff, 0xcc, 0x76, 0x64, 0x77, 0x30, 0x3c, 0x08, 0x5d, 0x63, 0x96,
	0x76, 0x5a, 0x84, 0xa7, 0x74, 0x9d, 0x14, 0xcf, 0x30, 0x89, 0xd1, 0xc1, 0x59, 0x13, 0xb0, 0xdd,
	0xf4, 0xe8, 0xf4, 0xd1, 0x1d, 0x81, 0x65, 0x70, 0xb5, 0x47, 0x12, 0x4a, 0xc7, 0x42, 0xa3, 0xf2,
	0x88, 0xab, 0x57, 0xb8, 0xdd, 0xa0, 0xd6, 0xf6, 0xc3, 0x7a, 0xbd, 0xdf, 0xa2, 0x3f, 0xa8, 0x2f,
	0x64, 0x1c, 0xa6, 0x5b, 0xd1, 0x9c, 0x75, 0x36, 0xe9, 0xf7, 0xcf, 0xa7, 0xbc, 0xff, 0x65, 0x71,
	0xf1, 0x32, 0xfb, 0xbc, 0x97, 0x76, 0xa9, 0x51, 0x78, 0xa3, 0x8c, 0x7c, 0xe8, 0xce, 0xb5, 0xab,
	0xab, 0x6a, 0x77, 0xd9, 0x8d, 0x8f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x52, 0xfd, 0x97, 0xe0,
	0x47, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloWorldServiceClient is the client API for HelloWorldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloWorldServiceClient interface {
	SayHelloWorld(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error)
}

type helloWorldServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloWorldServiceClient(cc *grpc.ClientConn) HelloWorldServiceClient {
	return &helloWorldServiceClient{cc}
}

func (c *helloWorldServiceClient) SayHelloWorld(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error) {
	out := new(HttpResponse)
	err := c.cc.Invoke(ctx, "/HelloWorldService/SayHelloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloWorldServiceServer is the server API for HelloWorldService service.
type HelloWorldServiceServer interface {
	SayHelloWorld(context.Context, *HttpRequest) (*HttpResponse, error)
}

func RegisterHelloWorldServiceServer(s *grpc.Server, srv HelloWorldServiceServer) {
	s.RegisterService(&_HelloWorldService_serviceDesc, srv)
}

func _HelloWorldService_SayHelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloWorldServiceServer).SayHelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HelloWorldService/SayHelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloWorldServiceServer).SayHelloWorld(ctx, req.(*HttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloWorldService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HelloWorldService",
	HandlerType: (*HelloWorldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHelloWorld",
			Handler:    _HelloWorldService_SayHelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
